function [useErrScope,usePoseView,SampleRate,imuFs] = scopes(useErrScope,usePoseView,SampleRate,imuFs)
    if useErrScope
        errscope = HelperScrollingPlotter( ...
                'NumInputs', 1, ...
                'TimeSpan', 10, ...
                'SampleRate', imuFs, ...
                'YLabel', {'degrees'}, ...
                'Title', {'Quaternion Distance'}, ...
                'YLimits', ...
                [-20, 20
                    ]);
    end
    
    if usePoseView
        viewer = HelperPoseViewer( ...
            'XPositionLimits', [-15, 15], ...
            'YPositionLimits', [-15, 15], ...
            'ZPositionLimits', [-5, 5], ...
            'ReferenceFrame', 'ENU');
    end

